# Generated by Django 5.2.5 on 2025-08-08 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autor',
            old_name='biogra',
            new_name='biografia',
        ),
        migrations.RenameField(
            model_name='autor',
            old_name='nacion',
            new_name='nacao',
        ),
    ]
