# Generated by Django 5.2.5 on 2025-08-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_editora_livro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='ano_publicado',
            field=models.DateField(),
        ),
    ]
