# Generated by Django 5.2.5 on 2025-08-21 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_livro_ano_publicado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='ano_publicado',
            field=models.IntegerField(),
        ),
    ]
